name: 'PackSquash'
github-token:
  action-input:
    input: token
    is-default: true
  permissions:
    actions: read
    actions-reason: to get latest artifact #Checkout: https://github.com/ComunidadAylas/PackSquash-action/blob/master/entrypoint.sh#L36
    
#Fixes #652
