version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    target-branch: int
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    target-branch: int
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    target-branch: int
