name: 'Setup .NET Core SDK'
outbound-endpoints:
  - fqdn: dotnetcli.blob.core.windows.net
    port: 443
    reason: to download dotnet
  - fqdn: dotnetcli.azureedge.net
    port: 443
    reason: to download dotnet