name: IntegrationTest

on:
  pull_request:
    branches:
      - int

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Integration test
      uses: docker://ghcr.io/nholuongut/integration-test/int:latest
      env:
        PAT: ${{ secrets.PAT }}