name: create pr

on:      
 workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: nholuongut/nholuongut-runner@v2
      - uses: actions/checkout@v2
      - name: Create commits
        run: |
          git config user.name 'Varun'
          git config user.email 'varunsh-coder@users.noreply.github.com'
          date +%s > report.txt
          git add .
          git commit -m "Add untracked file during workflow"
      - name: Uncommitted change
        run: date +%s > report.txt
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3