name: generate-docs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - mkdocs.yml
      - 'tools/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-awesome-pages-plugin
      - run: mkdocs gh-deploy --force