name: 'Setup Node.js environment'
#github-token is used only to pull node distributions from node-versions. Metadata permissions is present by default

outbound-endpoints:
  - fqdn: nodejs.org
    port: 443
    reason: to download node distribution