name: "Deploy to Firebase Hosting"
github-token:
  action-input:
    input: repoToken
    is-default: false
  permissions:
    pull-requests: write
    pull-requests-reason: to comment on PRs #Checkout: https://github.com/FirebaseExtended/action-hosting-deploy#repotoken-string

#Fixes #514
