name: "Apply version label to issue with specific label"
github-token:
  action-input:
    input: github-token
    is-default: false
  permissions:
    issues: write
    issues-reason: to label issues