name: 'Setup Go environment'
#github-token is used only to pull node distributions from go-versions. Metadata permissions is present by default

outbound-endpoints:
  - fqdn: storage.googleapis.com
    port: 443
    reason: to download Go archive
  - fqdn: golang.org
    port: 443
    reason: to confirm version
  - fqdn: api.github.com
    port: 443
    reason: to fetch manifest with go versions
  - fqdn: github.com
    port: 443
    reason: to download Go archive
nholuongut-runner-link: https://app.stepsecurity.io/github/nholuongut/agent/actions/runs/1523234844