name: 'Mypy'
github-token:
  action-input:
    input: github-token
    is-default: false
  permissions:
    checks: write #CHECKOUT: https://github.com/kolonialno/mypy-action/blob/031f9f60ff8ae4ec616c3fa63dc710d98d55a39f/index.js#L25
    checks-reason: to create & update check runs 
# FIX: #287