name: 'Close Issue'
github-token:
  action-input:
    input: token
    is-default: true
  permissions:
    issues: write
    issues-reason: to close issues
outbound-endpoints:
  - fqdn: api.github.com
    port: 443
    reason: to call GitHub Issues API 
