name: 'Issues Helper'
github-token:
  action-input:
    input: token
    is-default: true
  permissions:
    issues: write
    issues-reason: to update issues
    pull-requests: write
    pull-requests-reason: to update PRs
