name: "Snyk Infrastructure as Code"
outbound-endpoints:
  - fqdn: snyk.io
    port: 443
    reason: to authenticate with snyk
nholuongut-runner-link: https://app.stepsecurity.io/github/h0x0er/kb_setup/actions/runs/1711645290