name: 'Release Helper'
github-token:
  action-input:
    input: token
    is-default: true
  permissions:
    contents: write
    contents-reason: to create releases # Checkout: https://github.com/actions-cool/release-helper/blob/8e4c46438582511457992128fbaf9e5a959f2b0b/src/main.ts#L73

# Fix: #551
