name: 'Simple Issue Labeler'
github-token:
  action-input:
    input: repo-token
    is-default: true
  permissions:
    issues: write
    issues-reason: to label issues
    pull-requests: write
    pull-requests-reason: to label PRs