name: 'Checkout'
github-token:
  action-input:
    input: token
    is-default: true
  permissions:
    contents: read
    contents-reason: to fetch code
outbound-endpoints:
  - fqdn: github.com
    port: 443
    reason: to fetch code from GitHub