name: 'PR Welcome'
github-token:
  action-input:
    input: token
    is-default: true
  permissions:
    issues: write
    issues-reason: to create, update & react on issues #Checkout: https://github.com/actions-cool/pr-welcome/blob/main/src/main.js#L171
    pull-requests: write
    pull-requests-reason: to request reviewer #Checkout: https://github.com/actions-cool/pr-welcome/blob/main/src/main.js#L147
    
#Fixes #548
