name: 'AWS CloudFormation "Deploy CloudFormation Stack" Action for GitHub Actions'
outbound-endpoints:
  - fqdn: cloudformation.*.amazonaws.com
    port: 443
    reason: to call AWS cloud formation API
nholuongut-runner-link: https://app.stepsecurity.io/github/nholuongut/secure-repo/actions/runs/1537681246