name: "Infracost Actions"
github-token:
  action-input:
    input: github-token
    is-default: true
  permissions:
    pull-requests: write
    pull-requests-reason: to post comment on PR #Checkout: https://github.com/infracost/actions/blob/master/comment/action.yml#L18
    
#Fixes #617