name: 'Upload a Build Artifact'
outbound-endpoints:
  - fqdn: pipelines.actions.githubusercontent.com
    port: 443
    reason: to upload artifact
nholuongut-runner-link: https://app.stepsecurity.io/github/nholuongut/agent/actions/runs/1523253110