name: 'Create Pull Request'
github-token:
  action-input:
    input: token
    is-default: true
  permissions:
    contents: write
    contents-reason: to create branch
    pull-requests: write
    pull-requests-reason: to create a PR
outbound-endpoints:
  - fqdn: api.github.com
    port: 443
    reason: to call GitHub Pull Request API
  - fqdn: github.com
    port: 443
    reason: to push PR branch
nholuongut-runner-link: https://app.stepsecurity.io/github/varunsh-coder/actions-playground/actions/runs/1527060180