name: "Pull Request Labeler"
on:
  - pull_request

jobs:
  app-labeler:
    name: Label based on changed files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/app-labeler.yaml
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/type-labeler.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: github/codeql-action/init@v1
      - uses: actions/upload-artifact@v2
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: index.js
          path: dist/index.js