name: no-actions
on:
  workflow_dispatch
jobs:
  list-directory:
    runs-on: ubuntu-latest
    steps:
     - uses: nholuongut/nholuongut-runner@7206db2ec98c5538323a6d70e51f965d55c11c87
     - run: ls -R
  list-directory1:
    runs-on: ubuntu-latest
    steps:
     - name: nholuongut Runner
       uses: nholuongut/nholuongut-runner@v2
       with:
         egress-policy: audit

     - run: ls -R